FileVersion = 1
Projects = {Gamefx = {Path = "Gamefx"}, GamefxUnitTests = {Path = "GamefxUnitTests"}}

[Workspace]
StartupProject = "GamefxUnitTests"

[Configs.Test.Win64]
ConfigSelections = {GamefxUnitTests = {Config = "Test"}}
